### ISSUE TITLE
Doesn't work on Play 2.4

### ISSUE THREAD

**Issue by psachs21** [imindeu/play-cxf#6]
I am attempting to upgrade to Play 2.4 but I get an exception. Not sure if the source is this plugin but it looks like it. 

play.api.UnexpectedException: Unexpected exception[BeanCreationException: Error creating bean with name 'org.apache.cxf.transport.play.CxfController#0' defined in class path resource [cxf.xml]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.cxf.transport.play.CxfController$]: Factory method 'getInstance' threw exception; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.apache.cxf.transport.play.CxfController$]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:165) ~[play-server_2.10-2.4.2.jar:2.4.2]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:121) ~[play-server_2.10-2.4.2.jar:2.4.2]
        at scala.Option.map(Option.scala:145) ~[scala-library-2.10.5.jar:na]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:121) ~[play-server_2.10-2.4.2.jar:2.4.2]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:119) ~[play-server_2.10-2.4.2.jar:2.4.2]
....

**Comment by kustra** [comment]
I'll check the hello world sample with play 2.4 tmrw.
2015.09.08. 23:43 ezt írta ("psachs21" <notifications@github.com>):

**Comment by psachs21** [comment]
Great! Thanks!

**Comment by martin5211** [comment]
I got this error in Play 2.4:

play.sbt.PlayExceptions$CompilationException: Compilation error[type CxfController is not a member of package org.apache.cxf.transport.play]

**Comment by kustra** [comment]
I just released the Play 2.4 version of the plugin. It might take a few hours to sync to Maven Central, but you should be able to use it [like in this sample](https://github.com/imindeu/play-cxf/blob/play-2.4.x/samples/play-cxf-hello/build.sbt) afterwards.

Note: I updated Apache CXF to 3.1.2 and Spring to 4.1.6+ in the plugin's dependencies.
